const errorCodes = Object.freeze([
    "Successful request." ,
    "Requesting user is not an administrator!" ,
    "A query parameter is missing!" ,
    "Id not found!" ,
    "User not found!" ,
    "You don't have enough points!" ,
    "Discounts out of stock for this category!" ,
    "Internal server error." ,
    "Incorrect data inserted." ,
    "You have compiled all the available questions. Please come back later!" ,
    "You didn't provide a question." ,
    "The provided ID doesn't match any report." ,
    "The report has already been solved." ,
    "The services to this application has been restricted." ,
    "Authentication token missing." ,
    "Failed to authenticate token." ,
    "The email inserted does not exist.",
    "Your account has been banned!",
    "Registration request for this email already running!",
    "The inserted email has already been used!",
    "The inserted password is too weak.",
    "Invalid registration request!",
    "Registration code expired!",
    "Inserted registration code is wrong!",
    "Coordinates inserted not valid!",
    "The question type selected must contain options!",
    "The ID provided doesn't match any authenticated user!",
    "The password submitted is wrong!",
    "The searched item was not found.",
    "The insterted email is not valid"
]);


export default errorCodes;