openapi: 3.0.4
info:
  title: GreenMap API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 1.0.0

servers:
  - url: http://localhost:3000/api/v1/
    description: Optional server description, e.g. Main (production) server

paths:
  /login:
    get:
      summary: Returns a list of all authenticated users.
      description: Optional extended description in CommonMark or HTML.
      responses:
        "200": # status code
          description: A JSON array of AuthenticatedUser objects
          content:
            application/json:
              schema:
                type: object 
                properties:
                    passwordHash:
                      type: string
                    email:
                      type: string
                    banned:
                      type: boolean
                    administrator:
                      type: boolean
                    points:
                      type: integer
                example: # Sample data
                  passwordHash: "DfajfkajioFUWAopa"
                  email: "example@email.com"
                  banned: false
                  administrator: false
                  points: 0
    post:
      summary: Returns a JWT token if the login is successful.
      description: Optional extended description in CommonMark or HTML.
      responses:
        "200": # status code
          description: A JSON containing the JWT token
          content:
            application/json:
              schema:
                type: string 
              example: # Sample data
                authToken: "KvNopad-ffoPF+FJgkfjfv"
    delete:
      summary: Deletes all authenticated users.
      description: Optional extended description in CommonMark or HTML.
      responses:
        "204": # status code
          description: A JSON confirming the deletion of the users
          content:
            application/json:
              schema:
                type: string 
              example: # Sample data
                authToken: "UTENTI AUTENTICATI CANCELLATI"
  /register:
    get:
      summary: Returns a list of all registering users.
      description: Optional extended description in CommonMark or HTML.
      responses:
        "200": # status code
          description: A JSON array of RegisteringUser objects
          content:
            application/json:
              schema:
                type: object 
                properties:
                    passwordHash:
                      type: string
                    email:
                      type: string
                    verificationCode:
                      type: object 
                      properties:
                        code:
                          type: integer
                        expireDate:
                          type: string
                example: # Sample data
                  passwordHash: "DfajfkajioFUWAopa"
                  email: "example@email.com"
                  verificationCode:
                    code: 123456
                    expireDate: "21/05/2025 23:59:59"
  /trashcans:
    get:
      summary: Returns a list of all trashcans.
      description: Optional extended description in CommonMark or HTML.
      responses:
        "200": # status code
          description: A JSON array of Trashcan objects
          content:
            application/json:
              schema:
                type: object 
                properties:
                    latitude:
                      type: number
                    longitude:
                      type: number
                    trashcanType:
                      type: integer
                example: # Sample data
                  latitude: 46.06146267294853
                  longitude: 11.117831247229145
                  trashcanType: 2
    get:
      summary: Returns the nearest trashcan of the specified type.
      responses:
        "200": #success status code
          description: A trashcan object.
          content:
            application/json:
              schema:
                type: object 
                properties:
                    latitude:
                      type: number
                    longitude:
                      type: number
                    trashcanType:
                      type: integer